### ISSUE TITLE
Website missing root page

### ISSUE THREAD

**Issue by mikehaller** [eclipse-leda/leda#56]
When opening https://eclipse-leda.github.io/ a 404 appears.
There should be a redirect to `/leda`

Note: full page is generated by GH Pages, need to check how to add the root index page.

**Comment by mikehaller** [comment]
Requires an additional repository according to [GitHub Pages documentation](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3350)

Created an Eclipse Helpdesk Issue for a new repo: <https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3350>

**Comment by vasilvas99** [comment]
Now a landing page exists: https://github.com/eclipse-leda/eclipse-leda.github.io
